# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: warehouse
services:
  app:
    image: warehouse
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs,no-liquibase
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/wareHouse
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/wareHouse
    deploy:
      restart_policy:
        condition: any
      replicas: 1
    networks:
      - external
      - internal
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: postgresql-prod.yml
      service: postgresql

networks:
  internal:
  external:
