export enum Status {
  BANG_TUONG_WARE_HOUSE = 'BANG_TUONG_WARE_HOUSE',
  LOADED_ON_VEHICLE = 'LOADED_ON_VEHICLE',
  ARRIVED_AT_HN = 'ARRIVED_AT_HN',
  DELIVERED = 'DELIVERED',
  CUSTOMER_SIGNED = 'CUSTOMER_SIGNED',
  CANCELED = 'CANCELED',
}
